### PR TITLE
Implemented a way to listen to editor updates

### PR DESCRIPTION
**Pull request by jpg-gamepad**
I was trying to implement autosave locally and the updateListener kept triggering (when showing and removing ghosts). This update should help others.

### CODE REVIEW

**Comment by tmcw** [comment]
I think this duplicative of `shouldTakeUpdate`, which is exported from the current package, and the `copilotIgnore` annotation - https://github.com/val-town/codemirror-codeium/blob/main/ARCHITECTURE.md#ghost-text

**Comment by jpg-gamepad** [comment]
How do you use `shouldTakeUpdate` and `copilotIgnore` with the updateListener?
I ended up assigning userEvent labels to the three events, just so I could build out an auto-save/refresh system in my local app.

Thank you for this btw! It was hard to find something that actually worked!

**Comment by tmcw** [comment]
It'd work like this - `shouldTakeUpdate` returns true if the change is from the user and not from codeium.

```ts
new EditorView({
  extensions: [
    EditorView.updateListener.of((v) => {
      if (shouldTakeUpdate(v) {
        // Use the current document state
        console.log(v.state.doc.toString());
      }
    });
  ]
);
```

**Comment by jpg-gamepad** [comment]
I see it!
Thank you!

**Pull request closed without merging**
